### ISSUE TITLE
Email Never gets sent

### ISSUE THREAD

**Issue by sephma** [lsgs/redcap-report-scheduler#1]
Hi @lsgs 

 This is a really great tool and will definitely solve some internal data sharing issues for us. I've tested the config in a dozen different ways, but the cron job never seems to run. Anything specific that I should focus on for troubleshooting? Let me know if there is anything I can send that would help troubleshoot.

Thanks,
Sean

**Comment by lsgs** [comment]
Hello @sephma. Check your redcap_crons table and you should see a record in there for the module's cron task, and when it last ran. If you've set up a scheduled report in a project tick the box for additional logging (in the project module settings) and loog at what you get written to the redcap_external_modules_log table. HTH

**Comment by sephma** [comment]
@lsgs Maybe it's getting caught up by shib??? What I'm seeing in the external_modules_log appears to be html of our university login page. The cron appears to be firing as expected.

**Comment by lsgs** [comment]
Interesting @sephma. I'm not familiar with shib auth but the way the module works is for the cron task to kick off a separate request to a module page for each project the module is activated in. It puts the kind of thing below out in the log - it has NOAUTH so it should bypass the auth process but I don't know if ship causes different behaviour. Can you find anything about that in the community site perhaps?

Scheduled Report processing complete for project id=9999
https://redcap.yourplace.edu/redcap_vx.y.z/ExternalModules/?prefix=report_scheduler&page=run_project_reports&NOAUTH&pid=9999
{"not_due":0,"sent":0,"failed":0}

**Comment by lsgs** [comment]
@sephma any luck yet? I notice I just get a login page when I try your link: https://redcap.youplace.edu/redcap_v10.3.x/ExternalModules/?prefix=report_scheduler&page=run_project_reports&NOAUTH&pid=2333 Why does ship get in the way of that?

I remembered after seeing my comment in ReportScheduler.php that it doesn't work if you try using the versionless (API) module page endpoint.

**Comment by lsgs** [comment]
Do you have access to the REDCap Community site @sephma ? Another shib user had problems and worked out a solution:
[https://community.projectredcap.org/questions/95489/report-schedule-issue-rc-v10010.html](https://community.projectredcap.org/questions/95489/report-schedule-issue-rc-v10010.html) 

> We figured it out. Our Shibboleth is protecting the ExternalModules folder. We don't want to open that folder up to cron jobs. We wrote a Shibb override that allows it to work for this module. It's working GREAT.
