### ISSUE TITLE
Error: The Project Id cannot be null! while saving specific user role rights.

### ISSUE THREAD

**Issue by biggeeves** [lsgs/redcap-report-scheduler#2]
I'm trying to get a report out once a month.  The E.M. isn't working yet.  I configured it to use "Require module-specific user privileges" in hopes it would work.  It threw an error which was emailed to me:.  Note I was also on the URL ending in redcap_v10.0.23/UserRights/index.php?pid=29 and the error specifies Project Id cannot be null!  This may be an issue with the E.M. framework...

[This message was automatically generated by REDCap]

The 'report_scheduler' module threw the following exception when calling the hook method 'redcap_module_save_configuration':

Exception: The Project Id cannot be null! in D:\redcap\redcap_v10.0.23\ExternalModules\classes\ExternalModules.php:2142
Stack trace:
#0 \redcap\redcap_v10.0.23\ExternalModules\classes\framework\Framework.php(110): ExternalModules\ExternalModules::getProjectSettingsAsArray('report_schedule...', '')
#1 [internal function]: ExternalModules\Framework->getProjectSettings('')
#2 \redcap\redcap_v10.0.23\ExternalModules\classes\framework\Framework.php(173): call_user_func_array(Array, Array)
#3 \redcap\redcap_v10.0.23\ExternalModules\classes\AbstractExternalModule.php(1234): ExternalModules\Framework->callFromModuleInstance('getProjectSetti...', Array)
#4 \redcap\modules\report_scheduler_v1.1.1\ReportScheduler.php(251): ExternalModules\AbstractExternalModule->__call('getProjectSetti...', Array)
#5 [internal function]: MCRI\ReportScheduler\ReportScheduler->redcap_module_save_configuration('')
#6 \redcap\redcap_v10.0.23\ExternalModules\classes\ExternalModules.php(2698): call_user_func_array(Array, Array)
#7 \redcap\redcap_v10.0.23\ExternalModules\classes\ExternalModules.php(2845): ExternalModules\ExternalModules::startHook('report_schedule...', 'v1.1.1', Array)
#8 \redcap\redcap_v10.0.23\ExternalModules\classes\ExternalModules.php(2859): ExternalModules\ExternalModules::ExternalModules\{closure}('report_schedule...', 'v1.1.1')
#9 \redcap\redcap_v10.0.23\ExternalModules\manager\ajax\save-settings.php(40): ExternalModules\ExternalModules::callHook('module_save_con...', Array, 'report_schedule...')
#10 {main}

URL: https://xyz.org/redcap_v10.0.23/ExternalModules/manager/ajax/save-settings.php?pid=&moduleDirectoryPrefix=report_scheduler

**Comment by lsgs** [comment]
I think I fixed this @biggeeves. Look out for v1.1.2 through the REDCap repo.
