### ISSUE TITLE
Module stopped working on module upgrade

### ISSUE THREAD

**Issue by jasonlones23** [lsgs/redcap-report-scheduler#7]
Module stopped working on upgrade to v1.2.2 on REDCap version 12.4.31.  Does the latest version of the module only work on PHP8?  This was in our test environment, and unfortunately, we can no longer get v1.1.2 from the repo.

**Comment by lsgs** [comment]
I can confirm that the module is working with my PHP 8.1.1 and REDCap v13.2.2 @jasonlones23. I released v1.3.1 today, which was tested with those versions. Please let me know if you continue to experience problems, and include any output you get from the logging from the Control Centre test page. Thanks.
