### ISSUE TITLE
Module fails to grab user's email address

### ISSUE THREAD

**Issue by AndrewPoppe** [lsgs/redcap-report-scheduler#8]
When saving project configuration, the module no longer pulls the "from" email address for the selected user. This causes reports to fail to send.

**EDIT: the explanation below may or may not be right**
---
Not sure when this bug was introduced, but I think this is because of this line:
https://github.com/lsgs/redcap-report-scheduler/blob/5b96718ebe4db74cb5d4590b68e272ecc6efac7d/ReportScheduler.php#L195

Since the parameterized call inserts quotes into the query around its parameters, it can't be used to insert column names into SELECT queries.

**Comment by lsgs** [comment]
Thanks for reporting @AndrewPoppe. Please try v1.3.2 which contains a fix for this.
